/* ============================================================================
   ESDMK · Glossary — registered on window.ESDMK_GLOSSARY.
   Compact bilingual term list covering the four UAS topics + Demographic
   Transition background. Each term: { term, def: {en,id} }.
   ============================================================================ */
(function () {
  window.ESDMK_GLOSSARY = [

    /* ---- Topic 1: Schooling / human capital ---- */
    { term: 'Human capital',
      def: { en: 'Productive skills embodied in a worker, acquired through education, training and experience. The "asset" the schooling decision invests in.',
             id: 'Keterampilan produktif yang melekat pada pekerja, diperoleh melalui pendidikan, pelatihan, dan pengalaman.' } },
    { term: 'ENPV (Expected Net Present Value)',
      def: { en: 'Σ (w_t − C_t) / (1+r)^t. Discounted sum of net cash flows along an earnings path.',
             id: 'Σ (w_t − C_t) / (1+r)^t. Jumlah diskon arus kas neto sepanjang jalur pendapatan.' } },
    { term: 'IRR (Internal Rate of Return)',
      def: { en: 'Discount rate R that makes two earnings streams equal in present value. Adopt schooling iff R > r.',
             id: 'Tingkat diskon R yang menyamakan dua arus pendapatan dalam nilai sekarang. Sekolah iff R > r.' } },
    { term: 'MRR / MCC',
      def: { en: 'Marginal rate of return on schooling (= w′(s)/w(s), downward in s) vs marginal cost of capital (= r, horizontal). Optimum at intersection.',
             id: 'Tingkat pengembalian marjinal (= w′(s)/w(s)) vs biaya marjinal modal (= r). Optimum di perpotongan.' } },
    { term: 'Mincer earnings function',
      def: { en: 'ln w = α₁ + α₂·YOS + α₃·EXP + α₄·EXP² + ε. α₂ is the proportional return per year of schooling.',
             id: 'ln w = α₁ + α₂·YOS + α₃·EXP + α₄·EXP² + ε. α₂ = return proporsional per tahun sekolah.' } },
    { term: 'Opportunity cost of schooling',
      def: { en: 'The wage the worker would have earned during the years she is studying. Usually the largest component of total cost.',
             id: 'Upah yang akan diperoleh pekerja selama tahun ia belajar. Biasanya komponen biaya terbesar.' } },
    { term: 'Ability bias',
      def: { en: 'Upward bias in the OLS Mincer return: high-ability people both study more and earn more, so some of the ability premium is attributed to schooling.',
             id: 'Bias ke atas dalam return OLS Mincer: orang berkemampuan tinggi belajar lebih banyak dan berpenghasilan lebih.' } },
    { term: 'Signalling (Spence 1973)',
      def: { en: 'Theory that schooling does not raise productivity but reveals existing ability because high types find school cheaper. Sheepskin effect = wage jump at degree completion.',
             id: 'Teori bahwa sekolah tidak menaikkan produktivitas tetapi mengungkapkan kemampuan yang ada. Efek sheepskin = lonjakan upah pada penyelesaian gelar.' } },
    { term: 'General vs specific training',
      def: { en: 'General training raises productivity at any employer (worker pays, worker reaps). Specific training only at the current employer (cost & benefit shared with firm).',
             id: 'Pelatihan umum menaikkan produktivitas di mana saja; pelatihan khusus hanya di perusahaan saat ini.' } },

    /* ---- Topic 2: CWD ---- */
    { term: 'Compensating wage differential (CWD)',
      def: { en: 'Wage premium required to make a worker indifferent between a clean job and a job with disamenity x. CWD = w₁ − w₀ s.t. U(w₀,x₀) = U(w₁,x₁).',
             id: 'Premium upah agar pekerja indiferen antara pekerjaan bersih dan pekerjaan dengan disamenity x.' } },
    { term: 'Hedonic wage function',
      def: { en: 'Equilibrium relationship w = h(x), h′ > 0. Worker FOC: h′(x*) = MRS_{xw} = marginal willingness to accept.',
             id: 'Hubungan keseimbangan w = h(x), h′ > 0. FOC pekerja: h′(x*) = MRS.' } },
    { term: 'Total compensation',
      def: { en: 'TC = wage + PV(benefits) − MWTP(disamenity). Equilibrium equalises TC across jobs of equal skill, not the wage alone.',
             id: 'TC = upah + NS(tunjangan) − MWTP(disamenity).' } },
    { term: 'Sorting / self-selection',
      def: { en: 'Workers choose the job where their IC is tangent to the hedonic locus. Risk-tolerant sort to high-x; risk-averse to low-x.',
             id: 'Pekerja memilih pekerjaan tempat IC tangen pada lokus hedonik.' } },
    { term: 'Monopsony',
      def: { en: 'A market structure with few buyers of labour, allowing employers to set wages below the marginal product. Used to explain why gig wages may sit below the CWD level.',
             id: 'Struktur pasar dengan sedikit pembeli tenaga kerja.' } },

    /* ---- Topic 3: Discrimination ---- */
    { term: 'Taste-based discrimination (Becker)',
      def: { en: 'Employer/employee/customer has a "taste" against a group g; acts as if their wage were w_g(1+d) where d = discrimination coefficient.',
             id: 'Pengusaha/rekan/konsumen memiliki "selera" terhadap kelompok g; bertindak seolah upah w_g(1+d).' } },
    { term: 'Discrimination coefficient d',
      def: { en: 'Percentage mark-up the prejudiced employer adds to the disliked group\'s wage. Bigger d = stronger prejudice.',
             id: 'Mark-up persentase pengusaha berprasangka.' } },
    { term: 'Nepotism coefficient n',
      def: { en: 'Symmetric to d but applied to the favoured group: utility-adjusted wage = w_g(1-n).',
             id: 'Simetris dengan d untuk kelompok yang difavoritkan: upah = w_g(1−n).' } },
    { term: 'Becker hiring rule',
      def: { en: 'Hire only F if w_F(1+d) < w_M, only M if reversed. Generates firm-level segregation but reduces profit.',
             id: 'Rekrut F saja jika w_F(1+d) < w_M, M saja sebaliknya.' } },
    { term: 'Statistical discrimination',
      def: { en: 'Employer uses group average ȳ_g and noisy individual signal T_i: ŷ_i = (1−α)ȳ_g + αT_i. Self-reinforcing under different group means or signal precision.',
             id: 'Pengusaha memakai rata-rata kelompok ȳ_g dan sinyal individu bising T_i.' } },
    { term: 'Oaxaca decomposition',
      def: { en: 'Δw̄ = [(α_M−α_F) + (β_M−β_F)s̄_F] + β_M(s̄_M−s̄_F). First bracket = discrimination, second = explained skill gap.',
             id: 'Δw̄ = [(α_M−α_F) + (β_M−β_F)s̄_F] + β_M(s̄_M−s̄_F).' } },
    { term: 'Wage gap (raw vs adjusted)',
      def: { en: 'Raw = w̄_M − w̄_F. Adjusted = raw minus explained component (Oaxaca). Cameron et al. 2015 Indonesia: raw 34.4%/50.2%, unexplained 62%/75%.',
             id: 'Mentah vs disesuaikan; ID: mentah 34,4%/50,2%, tak terjelaskan 62%/75%.' } },

    /* ---- Topic 4: Migration ---- */
    { term: 'Lewis dual-sector model',
      def: { en: 'Subsistence sector (rural, wage OS) coexists with capitalist sector (wage OW > OS). Capitalist hires from unlimited rural supply at OW until rural surplus exhausts (Lewis turning point).',
             id: 'Sektor subsisten dan sektor kapitalis hidup berdampingan; surplus tenaga kerja diserap pada upah tetap OW.' } },
    { term: 'Sjaastad PV inequality',
      def: { en: 'PV_{ij} = Σ (U_j^t − U_i^t − C_{ij}^t) / (1+r)^t > 0. Move to destination j with the largest PV.',
             id: 'PV_{ij} = Σ (U_j^t − U_i^t − C_{ij}^t) / (1+r)^t > 0.' } },
    { term: 'Psychic cost',
      def: { en: 'Non-monetary component of migration cost: separation, cultural unfamiliarity, expected disutility of abuse / discrimination at destination.',
             id: 'Komponen non-moneter biaya migrasi.' } },
    { term: 'Harris–Todaro expected wage',
      def: { en: 'E[W_u] = W_u · E_u/L_u. Equilibrium: E[W_u] = W_r ⇒ urban unemployment rate u* = 1 − W_r/W_u.',
             id: 'E[W_u] = W_u · E_u/L_u; keseimbangan u* = 1 − W_r/W_u.' } },
    { term: 'Tied mover / tied stayer (Mincer 1978)',
      def: { en: 'Tied mover: wife with G₂<0 moves anyway because G₁>|G₂|. Tied stayer: wife with G₂>0 stays because |G₁|>G₂. Family decision dominates individual.',
             id: 'Tied mover/stayer: keputusan keluarga mendominasi individu.' } },
    { term: 'New economics of migration (Stark)',
      def: { en: 'Household sends one earner abroad as a remittance / risk-diversification strategy. Family PV is positive even when individual PV is borderline.',
             id: 'Rumah tangga mengirim satu pencari nafkah ke luar negeri sebagai strategi remitansi.' } },
    { term: 'Gravity model',
      def: { en: 'M̂_{ij} = k · P_i P_j / d_{ij}^b. In logs: ln M̂_{ij} = a₀ + a₁ ln P_i + a₂ ln P_j − b ln d_{ij}. Extended with GDP, education, agriculture share, common border.',
             id: 'Model gravitasi standar untuk arus migrasi antar wilayah.' } },
    { term: 'Rogers–Castro age pattern',
      def: { en: 'Empirical age profile of migration: humped, peaks in early–mid 20s; declining for older adults. Contradicts the pure-PV monotonically declining prediction.',
             id: 'Profil usia migrasi berbenjol, puncak di awal–pertengahan 20-an.' } },
    { term: 'Push-pull (Lee 1966)',
      def: { en: 'Origin push (+/−) + destination pull (+/−) + intervening obstacles + personal factors. A move happens only if destination pulls outweigh origin pulls plus obstacles.',
             id: 'Faktor push asal + pull tujuan + hambatan intervening + faktor personal.' } },
    { term: 'BP2MI',
      def: { en: 'Badan Pelindungan Pekerja Migran Indonesia — the agency that registers, places and protects Indonesian migrant workers.',
             id: 'Badan Pelindungan Pekerja Migran Indonesia.' } },

    /* ---- Week 12: Demographic background ---- */
    { term: 'Demographic transition',
      def: { en: 'Four-stage shift from high birth & death rates (Stage 1) through population explosion (Stage 2) to low birth & death rates and population stabilisation (Stages 3–4).',
             id: 'Pergeseran empat tahap dari BR/DR tinggi ke BR/DR rendah dan stabilisasi penduduk.' } },
    { term: 'TFR (Total Fertility Rate)',
      def: { en: 'Synthetic-cohort average number of children a woman would have at current age-specific fertility rates. Replacement ≈ 2.1.',
             id: 'Rata-rata anak kohor sintetis pada ASFR sekarang. Penggantian ≈ 2,1.' } },
    { term: 'Dependency ratio',
      def: { en: '(pop 0–14 + pop 65+) / pop 15–64 × 100. Falls during demographic dividend window, rises again when ageing dominates.',
             id: '(0–14 + 65+) / 15–64 × 100.' } },
    { term: 'Bonus demografi',
      def: { en: 'Period when DR is low and the working-age share is large; first dividend = mechanical accounting, second = pre-retirement saving boost. Indonesia ≈ 2025–2035.',
             id: 'Periode rasio ketergantungan rendah dan pangsa usia kerja besar; ID ≈ 2025–2035.' } }
  ];
})();
