/* ============================================================================
   ESP — Past Exams (window.ESP_EXAMS). Two real UAS papers, worked 1:1, bilingual.
   Graph answers embed STATIC, math-exact FigLab SVGs (correct by construction).
   Loaded AFTER figlab.js + figures*.js so window.FigLab.svg is available.
   ============================================================================ */
(function () {
  'use strict';
  function FIG(id, o) {
    return (window.FigLab && window.FigLab.svg)
      ? '<div class="exam-fig">' + window.FigLab.svg(id, o || {}, 380, 290) + '</div>' : '';
  }

  window.ESP_EXAMS = {

    /* ===================== UAS 2023/2024 — 31 May 2024 (English) ===================== */
    '2024': {
      year: '2024',
      label: { en: 'Final Exam — 31 May 2024 (ECEU605100)', id: 'UAS — 31 Mei 2024 (ECEU605100)' },
      note: { en: 'Closed book, 2.5 hours, calculator allowed. Four 25-point problems: taxation true/false & a good tax system; program evaluation + in-kind vs cash; social insurance + tax incidence + the PAYG dependency ratio; welfare programs & labour supply.',
              id: 'Closed book, 2,5 jam, boleh kalkulator. Empat soal @25 poin: benar/salah perpajakan & sistem pajak yang baik; evaluasi program + in-kind vs tunai; jaminan sosial + insidensi pajak + rasio ketergantungan PAYG; program kesejahteraan & penawaran tenaga kerja.' },
      sections: [
        { label: { en: 'Essay (4 × 25)', id: 'Esai (4 × 25)' }, kind: 'essay', questions: [
          { n: 'I',
            q: { en: '<b>(a)</b> True or False, with theory + example/graph: (i) Everyone who earns labour income must pay income tax. (ii) If the government levies a unit tax on a monopoly, the firm can always shift the whole burden to consumers. (iii) A lump-sum tax is an efficient tax. <b>(b)</b> What are the characteristics of a good tax system?',
                 id: '<b>(a)</b> Benar/Salah, dgn teori + contoh/grafik: (i) Semua yang berpenghasilan kerja wajib bayar PPh. (ii) Jika pemerintah mengenakan pajak unit ke monopoli, perusahaan selalu bisa menggeser seluruh beban ke konsumen. (iii) Pajak lump-sum adalah pajak yang efisien. <b>(b)</b> Apa ciri sistem pajak yang baik?' },
            answer: { en: '(i) FALSE · (ii) FALSE · (iii) TRUE · (b) the 5 principles.', id: '(i) SALAH · (ii) SALAH · (iii) BENAR · (b) 5 prinsip.' },
            working: { en: '<p><b>(i) FALSE.</b> Income tax is <i>progressive</i> with a tax-free threshold (in Indonesia, <span class="key">PTKP</span> ≈ Rp 54 jt/yr). Earners below the threshold pay <b>zero</b>; informal-sector and many low earners owe no PPh. So not everyone who works pays income tax.</p>' +
                    '<p><b>(ii) FALSE.</b> Pass-through depends on elasticities, not on who is taxed. A profit-maximising monopolist sets MR = MC + t; with a linear demand the price rises by <i>less</i> than the unit tax, so the firm bears part of it. Only with perfectly inelastic demand (or special demand curvature) could 100% be shifted. "Always" is false.</p>' + FIG('tax-dwl', { bD: 0.9, bS: 0.9, t: 2 }) +
                    '<p><b>(iii) TRUE.</b> A <span class="key">lump-sum tax</span> is fixed regardless of behaviour, so it has <b>no marginal distortion</b> (no substitution effect) → <b>no deadweight loss</b> → efficient. Its drawback is equity/feasibility, not efficiency. (Contrast the wedge + DWL of the commodity tax above.)</p>' +
                    '<p><b>(b) A good tax system (Stiglitz / Rosen):</b></p><table><thead><tr><th>Principle</th><th>Meaning</th></tr></thead><tbody>' +
                    '<tr><td><b>Economic efficiency</b></td><td>Minimise distortion (small DWL).</td></tr>' +
                    '<tr><td><b>Fairness</b></td><td>Horizontal equity (equals treated equally) + vertical equity (more ability → more tax).</td></tr>' +
                    '<tr><td><b>Administrative simplicity</b></td><td>Low admin + compliance cost.</td></tr>' +
                    '<tr><td><b>Flexibility</b></td><td>Adapts to changing conditions.</td></tr>' +
                    '<tr><td><b>Political responsibility / transparency</b></td><td>Taxpayers can see what they pay.</td></tr></tbody></table>',
                 id: '<p><b>(i) SALAH.</b> PPh <i>progresif</i> dengan ambang bebas pajak (<span class="key">PTKP</span> ≈ Rp 54 jt/thn). Yang di bawah ambang membayar <b>nol</b>; pekerja informal & banyak berpenghasilan rendah tak terutang PPh. Jadi tidak semua yang bekerja membayar PPh.</p>' +
                    '<p><b>(ii) SALAH.</b> Pelimpahan pajak bergantung pada elastisitas, bukan pada siapa yang dipajaki. Monopolis menetapkan MR = MC + t; dengan permintaan linier, harga naik <i>kurang</i> dari pajak unit, sehingga perusahaan menanggung sebagian. Hanya dengan permintaan inelastis sempurna 100% bisa digeser. "Selalu" itu salah.</p>' + FIG('tax-dwl', { bD: 0.9, bS: 0.9, t: 2 }) +
                    '<p><b>(iii) BENAR.</b> <span class="key">Pajak lump-sum</span> tetap tanpa memandang perilaku, jadi <b>tanpa distorsi marginal</b> (tanpa efek substitusi) → <b>tanpa DWL</b> → efisien. Kelemahannya keadilan/kepraktisan, bukan efisiensi.</p>' +
                    '<p><b>(b) Sistem pajak yang baik (Stiglitz / Rosen):</b></p><table><thead><tr><th>Prinsip</th><th>Makna</th></tr></thead><tbody>' +
                    '<tr><td><b>Efisiensi ekonomi</b></td><td>Minimalkan distorsi (DWL kecil).</td></tr>' +
                    '<tr><td><b>Keadilan</b></td><td>Horizontal (yang sama diperlakukan sama) + vertikal (kemampuan lebih → pajak lebih).</td></tr>' +
                    '<tr><td><b>Kesederhanaan administrasi</b></td><td>Biaya admin + kepatuhan rendah.</td></tr>' +
                    '<tr><td><b>Fleksibilitas</b></td><td>Mudah menyesuaikan keadaan.</td></tr>' +
                    '<tr><td><b>Tanggung jawab politik / transparansi</b></td><td>Wajib pajak tahu yang dibayar.</td></tr></tbody></table>' } },

          { n: 'II',
            q: { en: 'Evaluating (i) free university and (ii) free meals for primary-school children: <b>(a)</b> analytical steps, data needed, other aspects to review. <b>(b)</b> Use a graph to show the effect of a free meal (in-kind) on the household budget constraint, vs a cash transfer equal to the meal’s rupiah value.',
                 id: 'Mengevaluasi (i) kuliah gratis dan (ii) makan gratis anak SD: <b>(a)</b> langkah analisis, data yang dibutuhkan, aspek lain. <b>(b)</b> Gambarkan efek makan gratis (in-kind) pada kendala anggaran rumah tangga, vs transfer tunai senilai rupiah makanan.' },
            answer: { en: '(a) CBA + target efficiency + externalities; (b) in-kind = kinked budget; cash = parallel shift.', id: '(a) CBA + efisiensi sasaran + eksternalitas; (b) in-kind = anggaran menekuk; tunai = geser sejajar.' },
            working: { en: '<p><b>(a) Analytical steps:</b> define objectives & beneficiaries → estimate <b>costs & benefits in present value</b> (cost-benefit analysis) → assess <b>allocative efficiency</b> (incentive effects, deadweight loss of the funding tax), <b>target efficiency</b> (leakage to the non-poor vs under-coverage of the poor), and <b>externalities</b> (education → higher productivity, lower crime; meals → child nutrition & human capital). Compare with the next-best alternative.</p>' +
                    '<p><b>Data needed:</b> unit cost per beneficiary, number & income profile of beneficiaries (targeting/leakage), take-up rates, and <b>outcomes</b> — enrolment/test scores/graduation for university; attendance, nutrition, learning for meals; plus the elasticity of behaviour (does free university just subsidise those who would enrol anyway?).</p>' +
                    '<p><b>Other aspects:</b> equity & distributional incidence, fiscal sustainability, administrative capacity (esp. informal sector), political feasibility, and behavioural responses / crowd-out of private spending.</p>' +
                    '<p><b>(b) In-kind vs cash.</b> Axes: subsidised good (food/meals) vs all other goods. A <b>cash</b> transfer of Rp F shifts the budget out <b>in parallel</b> (the blue line) — the family can spend it on anything. A <b>free meal</b> worth Rp F is <b>in-kind</b>: it only adds F of food, giving the <b>kinked A·H·M</b> budget (green). If the family already wanted ≥ F of food, the two are equivalent; if the meal forces <i>more</i> food than they’d choose, they are stuck at the corner <b>H</b> on a <i>lower</i> indifference curve than cash. So cash is weakly preferred by the recipient, but in-kind is chosen for <b>paternalism / targeting</b> (it guarantees the child is fed).</p>' + FIG('inkind-cash', { m: 10, F: 6, a: 0.2 }),
                 id: '<p><b>(a) Langkah analisis:</b> tetapkan tujuan & penerima → estimasi <b>biaya & manfaat dalam nilai sekarang</b> (CBA) → nilai <b>efisiensi alokatif</b> (efek insentif, DWL pajak pendana), <b>efisiensi sasaran</b> (kebocoran ke non-miskin vs under-coverage si miskin), dan <b>eksternalitas</b> (pendidikan → produktivitas naik, kriminalitas turun; makan → gizi anak & modal manusia). Bandingkan dgn alternatif terbaik berikutnya.</p>' +
                    '<p><b>Data:</b> biaya per penerima, jumlah & profil pendapatan penerima (sasaran/kebocoran), tingkat partisipasi, dan <b>hasil</b> — pendaftaran/nilai/kelulusan untuk kuliah; kehadiran, gizi, belajar untuk makan; serta elastisitas perilaku (apakah kuliah gratis hanya mensubsidi yang toh akan kuliah?).</p>' +
                    '<p><b>Aspek lain:</b> keadilan & insidensi distribusi, keberlanjutan fiskal, kapasitas administrasi (sektor informal), kelayakan politik, serta respons perilaku / crowd-out belanja swasta.</p>' +
                    '<p><b>(b) In-kind vs tunai.</b> Sumbu: barang bersubsidi (pangan) vs barang lain. Transfer <b>tunai</b> Rp F menggeser anggaran <b>sejajar</b> (garis biru) — bebas dibelanjakan. <b>Makan gratis</b> senilai Rp F bersifat <b>in-kind</b>: hanya menambah F pangan, memberi anggaran <b>menekuk A·H·M</b> (hijau). Jika keluarga toh ingin ≥ F pangan, keduanya setara; jika makanan memaksa <i>lebih</i> dari yang dipilih, mereka terjebak di sudut <b>H</b> pada kurva indiferen <i>lebih rendah</i> dari tunai. Jadi tunai sedikit lebih disukai penerima, tetapi in-kind dipilih demi <b>paternalisme / penyasaran</b> (menjamin anak makan).</p>' + FIG('inkind-cash', { m: 10, F: 6, a: 0.2 }) } },

          { n: 'III',
            q: { en: '<b>(a)</b> True/False: governments provide social insurance because markets fail to insure many key risks. <b>(b)</b> If labour supply is perfectly inelastic (vertical) and demand is normal/downward, and the textbook says the unemployment tax is paid entirely by employers — who actually pays? <b>(c)</b> The retiree:worker ratio is 1:5 now and will be 1:2 in 30 years. Under PAYG, if benefits stay the same what happens to the tax rate? If the tax rate stays the same, how much do benefits fall?',
                 id: '<b>(a)</b> Benar/Salah: pemerintah menyediakan jaminan sosial karena pasar gagal mengasuransikan banyak risiko penting. <b>(b)</b> Jika penawaran tenaga kerja inelastis sempurna (vertikal) dan permintaan normal/menurun, dan buku bilang pajak pengangguran ditanggung penuh oleh pemberi kerja — siapa sebenarnya yang membayar? <b>(c)</b> Rasio pensiunan:pekerja 1:5 sekarang dan 1:2 dalam 30 tahun. Dalam PAYG, jika manfaat tetap apa yang terjadi pada tarif pajak? Jika tarif tetap, berapa manfaat turun?' },
            answer: { en: '(a) TRUE; (b) workers bear it all; (c) tax ×2.5, or benefits fall 60%.', id: '(a) BENAR; (b) pekerja menanggung semua; (c) pajak ×2,5, atau manfaat turun 60%.' },
            working: { en: '<p><b>(a) TRUE.</b> Private markets fail for the most important risks: longevity (the <span class="key">annuity</span> market unravels through adverse selection), health (adverse selection + moral hazard), and unemployment (correlated, non-diversifiable risk + moral hazard). Government social insurance pools everyone and can mandate participation, overcoming adverse selection.</p>' +
                    '<p><b>(b) Workers bear the entire tax.</b> Statutory incidence ≠ economic incidence. With a <b>vertical (perfectly inelastic) labour supply</b>, the quantity of labour cannot change, so the tax cannot be shifted: the wage <i>workers receive</i> falls by the full tax while the wage <i>firms pay</i> is unchanged. The inelastic side bears 100% — exactly the land-tax logic below (vertical supply ⇒ supplier bears all, zero deadweight loss).</p>' + FIG('ptax-land', { Qbar: 6, t: 2 }) +
                    '<p><b>(c) PAYG algebra.</b> Balance: $B = t\\,(N_w/N_b)\\,w$, so $t = (N_b/N_w)(B/w)$. The dependency ratio rises from $N_b/N_w = 1/5 = 0.2$ to $1/2 = 0.5$.</p>' +
                    '<div class="formula">$$ \\frac{t_{new}}{t_{old}} = \\frac{0.5}{0.2} = 2.5 $$</div>' +
                    '<p>If <b>benefits stay the same</b>, the tax rate must rise <b>2.5×</b> (e.g. 10% → 25%). If instead the <b>tax rate stays the same</b>, benefits scale with $N_w/N_b$: $B_{new}/B_{old} = 2/5 = 0.4$, a <b>60% cut</b> in benefits. This is the demographic squeeze of an ageing population.</p>',
                 id: '<p><b>(a) BENAR.</b> Pasar swasta gagal untuk risiko terpenting: umur panjang (pasar <span class="key">anuitas</span> runtuh karena adverse selection), kesehatan (adverse selection + moral hazard), dan pengangguran (risiko berkorelasi + moral hazard). Jaminan sosial pemerintah menyatukan semua orang dan dapat mewajibkan kepesertaan, mengatasi adverse selection.</p>' +
                    '<p><b>(b) Pekerja menanggung seluruh pajak.</b> Insidensi hukum ≠ insidensi ekonomi. Dengan <b>penawaran tenaga kerja vertikal (inelastis sempurna)</b>, kuantitas tak bisa berubah, jadi pajak tak bisa digeser: upah <i>yang diterima pekerja</i> turun penuh sebesar pajak sedangkan upah <i>yang dibayar perusahaan</i> tetap. Sisi inelastis menanggung 100% — persis logika pajak tanah di bawah (penawaran vertikal ⇒ penjual menanggung semua, DWL nol).</p>' + FIG('ptax-land', { Qbar: 6, t: 2 }) +
                    '<p><b>(c) Aljabar PAYG.</b> Keseimbangan: $B = t\\,(N_w/N_b)\\,w$, jadi $t = (N_b/N_w)(B/w)$. Rasio ketergantungan naik dari $N_b/N_w = 1/5 = 0,2$ ke $1/2 = 0,5$.</p>' +
                    '<div class="formula">$$ \\frac{t_{baru}}{t_{lama}} = \\frac{0,5}{0,2} = 2,5 $$</div>' +
                    '<p>Jika <b>manfaat tetap</b>, tarif pajak harus naik <b>2,5×</b> (mis. 10% → 25%). Jika sebaliknya <b>tarif tetap</b>, manfaat menyusut sesuai $N_w/N_b$: $B_{baru}/B_{lama} = 2/5 = 0,4$, yaitu <b>turun 60%</b>. Inilah tekanan demografi populasi menua.</p>' } },

          { n: 'IV',
            q: { en: 'Welfare programs can change the decision to work. Use graphs. <b>(a)</b> A cash transfer of $100/month to non-working poor families, reduced 30% for every extra dollar earned — effect on the decision to work and hours? <b>(b)</b> If the clawback is 100%, does the program affect <i>all</i> families’ labour supply?',
                 id: 'Program kesejahteraan dapat mengubah keputusan kerja. Gunakan grafik. <b>(a)</b> Transfer tunai $100/bln ke keluarga miskin yang tak bekerja, dipotong 30% tiap tambahan dolar penghasilan — efek pada keputusan kerja dan jam kerja? <b>(b)</b> Jika potongan 100%, apakah program memengaruhi penawaran tenaga kerja <i>semua</i> keluarga?' },
            answer: { en: '(a) income + mild substitution effect → work a bit less; (b) only families in the phase-out range — not all.', id: '(a) efek pendapatan + substitusi ringan → kerja sedikit berkurang; (b) hanya keluarga di rentang phase-out — tidak semua.' },
            working: { en: '<p><b>(a) 30% clawback.</b> The guarantee creates an <b>income effect</b> (less need to work) and the 30% taper is an <b>implicit tax</b> on earnings, a <b>substitution effect</b> against work. But the phase-out slope stays <b>positive at 0.7·w</b>, so work still pays — the disincentive is moderate. Expect a modest fall in hours and some non-workers staying out, but most keep working.</p>' + FIG('welfare-bc', { w: 10, G: 100, t: 0.3, D: 0 }) +
                    '<p><b>(b) 100% clawback.</b> Now each $1 earned removes $1 of benefit, so net income is <b>flat</b> in the phase-out range — working there brings <b>nothing</b> (the <span class="key">welfare trap</span>). But it does <b>not</b> affect <i>all</i> families: only those whose earnings fall in the phase-out range (here $0–$100) face the trap. Families who can’t/don’t work just take the $100; families who would earn well <i>above</i> the break-even face the normal wage slope again and are unaffected. So the labour-supply distortion is concentrated on the low-earning margin, not universal.</p>' + FIG('welfare-bc', { w: 10, G: 100, t: 1, D: 0 }),
                 id: '<p><b>(a) Potongan 30%.</b> Jaminan menimbulkan <b>efek pendapatan</b> (kurang perlu bekerja) dan taper 30% adalah <b>pajak implisit</b> atas penghasilan, <b>efek substitusi</b> melawan kerja. Tetapi kemiringan phase-out tetap <b>positif 0,7·w</b>, jadi kerja tetap membayar — disinsentif moderat. Perkiraan: jam kerja turun sedikit dan sebagian tak bekerja, tetapi mayoritas tetap bekerja.</p>' + FIG('welfare-bc', { w: 10, G: 100, t: 0.3, D: 0 }) +
                    '<p><b>(b) Potongan 100%.</b> Kini tiap $1 penghasilan menghapus $1 manfaat, jadi pendapatan bersih <b>datar</b> di rentang phase-out — bekerja di situ <b>sia-sia</b> (<span class="key">jebakan bansos</span>). Tetapi <b>tidak</b> memengaruhi <i>semua</i> keluarga: hanya yang penghasilannya jatuh di rentang phase-out (di sini $0–$100) terkena jebakan. Keluarga yang tak bisa/tak bekerja cukup menerima $100; keluarga yang penghasilannya jauh <i>di atas</i> titik impas kembali ke kemiringan upah normal dan tak terpengaruh. Jadi distorsi terpusat pada margin berpenghasilan rendah, bukan universal.</p>' + FIG('welfare-bc', { w: 10, G: 100, t: 1, D: 0 }) } }
        ] }
      ]
    },

    /* ===================== UAS 2022/2023 — 9 June 2023 (Indonesian) ===================== */
    '2023': {
      year: '2023',
      label: { en: 'UAS — 9 June 2023 (ECEU605100)', id: 'UAS — 9 Juni 2023 (ECEU605100)' },
      note: { en: 'Closed book, 2.5 hours, calculator allowed. Four 25-point problems: cost-benefit analysis & discounting; a basic-income labour-supply budget constraint; Social Security behaviour + the two-period saving model; and free public health care across willingness-to-pay groups.',
              id: 'Closed book, 2,5 jam, boleh kalkulator. Empat soal @25 poin: analisis biaya-manfaat & diskonto; kendala anggaran tenaga kerja bantuan dasar; perilaku Jaminan Sosial + model tabungan dua periode; dan layanan kesehatan publik gratis lintas kelompok.' },
      sections: [
        { label: { en: 'Essay (4 × 25)', id: 'Esai (4 × 25)' }, kind: 'essay', questions: [
          { n: 'I',
            q: { en: 'Climate mitigation CBA: a policy costs Rp 50 T now and avoids Rp 500 T of environmental damage, but only 100 years from now. <b>(a)</b> Pros and cons. <b>(b)</b> Consultant X says invest the Rp 50 T at 6%/yr and use the proceeds to repair the damage later — is X right from a <i>financial</i> CBA view? <b>(c)</b> As an economist, do you agree with X? <b>(d)</b> If instead Rp 20 T is spent on prevention (avoiding Rp 300 T over 100 yr) and Rp 30 T is invested at 6% to repair at year 100 — what is the financial benefit-cost ratio? Do you agree?',
                 id: 'CBA mitigasi iklim: kebijakan berbiaya Rp 50 T sekarang dan menghindari Rp 500 T kerusakan lingkungan, tetapi baru 100 tahun lagi. <b>(a)</b> Kelebihan & kekurangan. <b>(b)</b> Konsultan X: investasikan Rp 50 T pada 6%/thn dan pakai hasilnya untuk memperbaiki kerusakan nanti — benarkah X dari sisi CBA <i>finansial</i>? <b>(c)</b> Sebagai ekonom, setuju dgn X? <b>(d)</b> Jika Rp 20 T untuk pencegahan (menghindari Rp 300 T selama 100 thn) dan Rp 30 T diinvestasikan pada 6% untuk perbaikan di tahun ke-100 — berapa rasio benefit-cost finansial? Setuju?' },
            answer: { en: '(b) X is right financially (the fund ≫ the benefit); B/C of mitigation ≈ 0.03; (d) B/C ≈ 0.62; but social CBA needs a lower discount rate.', id: '(b) X benar secara finansial (dana ≫ manfaat); B/C mitigasi ≈ 0,03; (d) B/C ≈ 0,62; tetapi CBA sosial perlu diskonto lebih rendah.' },
            working: { en: '<p>The key is <b>discounting</b>: $(1.06)^{100} \\approx 339.3$, so a rupiah 100 years out is worth almost nothing today.</p>' +
                    '<p><b>(a)</b> Pro: addresses a real, large, intergenerational problem; nominal benefit (Rp 500 T) is 10× the cost. Con: the benefit is <b>100 years away</b>, so its present value is tiny once discounted; deep uncertainty over a century; opportunity cost of Rp 50 T now.</p>' +
                    '<div class="formula">$$ PV(\\text{benefit}) = \\frac{500}{(1.06)^{100}} = \\frac{500}{339.3} \\approx \\text{Rp } 1.47\\text{ T}, \\quad B/C = \\frac{1.47}{50} \\approx 0.03 $$</div>' +
                    '<p>Financially the mitigation alone fails badly (B/C ≪ 1).</p>' +
                    '<p><b>(b) X is right — financially.</b> Investing Rp 50 T at 6% for 100 years grows to $50 \\times 339.3 \\approx$ <b>Rp 16,965 T</b>, vastly more than the Rp 500 T of damage to repair. Earning the market return dominates a project whose benefit is so far off, so a pure financial CBA favours X.</p>' +
                    '<p><b>(c) As an economist — disagree with treating it as purely financial.</b> The 6% market rate is the wrong <span class="key">social discount rate</span> for a 100-year climate problem (intergenerational equity — Stern ≈ 1.4% vs Nordhaus ≈ 4–6%). Financial CBA also ignores <b>non-market environmental value</b>, <b>irreversibility</b> (damage may not be repairable with money later), and <b>catastrophic tail risk</b>. A <i>social</i> CBA with a low discount rate and these factors can justify mitigation even when the financial one rejects it.</p>' +
                    '<p><b>(d)</b> Cost = Rp 50 T (20 prevention + 30 invested). Benefits: prevention avoids Rp 300 T at year 100 → $PV = 300/339.3 \\approx$ Rp 0.88 T; the Rp 30 T invested grows to $30 \\times 339.3 \\approx$ Rp 10,179 T at year 100 (its $PV =$ Rp 30 T, since it earns the discount rate).</p>' +
                    '<div class="formula">$$ B/C = \\frac{0.88 + 30}{50} = \\frac{30.88}{50} \\approx 0.62 $$</div>' +
                    '<p>Still &lt; 1 financially, but far better than 0.03 — because the <i>invested</i> portion at least returns its value while prevention is nearly worthless once discounted. Agreeing depends on whether you accept the 6% rate; on social-CBA grounds (irreversibility, low discount rate) prevention may still be worth more than the number suggests.</p>',
                 id: '<p>Kuncinya <b>diskonto</b>: $(1{,}06)^{100} \\approx 339{,}3$, jadi satu rupiah 100 tahun lagi nyaris tak bernilai hari ini.</p>' +
                    '<p><b>(a)</b> Plus: menangani masalah nyata, besar, antargenerasi; manfaat nominal (Rp 500 T) 10× biaya. Minus: manfaat <b>100 tahun lagi</b>, jadi nilai sekarangnya kecil setelah didiskonto; ketidakpastian seabad; biaya peluang Rp 50 T kini.</p>' +
                    '<div class="formula">$$ PV(\\text{manfaat}) = \\frac{500}{(1{,}06)^{100}} = \\frac{500}{339{,}3} \\approx \\text{Rp } 1{,}47\\text{ T}, \\quad B/C = \\frac{1{,}47}{50} \\approx 0{,}03 $$</div>' +
                    '<p>Secara finansial mitigasi saja gagal jauh (B/C ≪ 1).</p>' +
                    '<p><b>(b) X benar — secara finansial.</b> Menginvestasikan Rp 50 T pada 6% selama 100 tahun tumbuh menjadi $50 \\times 339{,}3 \\approx$ <b>Rp 16.965 T</b>, jauh lebih besar dari Rp 500 T kerusakan. Memperoleh imbal hasil pasar mengalahkan proyek yang manfaatnya begitu jauh, jadi CBA finansial murni mendukung X.</p>' +
                    '<p><b>(c) Sebagai ekonom — tidak setuju memperlakukannya murni finansial.</b> Tarif pasar 6% adalah <span class="key">tingkat diskonto sosial</span> yang keliru untuk masalah iklim 100 tahun (keadilan antargenerasi — Stern ≈ 1,4% vs Nordhaus ≈ 4–6%). CBA finansial juga mengabaikan <b>nilai lingkungan non-pasar</b>, <b>ireversibilitas</b> (kerusakan mungkin tak bisa diperbaiki dengan uang), dan <b>risiko ekor katastrofik</b>. CBA <i>sosial</i> dengan diskonto rendah dapat membenarkan mitigasi walau CBA finansial menolaknya.</p>' +
                    '<p><b>(d)</b> Biaya = Rp 50 T (20 pencegahan + 30 investasi). Manfaat: pencegahan menghindari Rp 300 T di tahun 100 → $PV = 300/339{,}3 \\approx$ Rp 0,88 T; Rp 30 T tumbuh menjadi $30 \\times 339{,}3 \\approx$ Rp 10.179 T di tahun 100 (PV-nya = Rp 30 T, karena memperoleh tarif diskonto).</p>' +
                    '<div class="formula">$$ B/C = \\frac{0{,}88 + 30}{50} = \\frac{30{,}88}{50} \\approx 0{,}62 $$</div>' +
                    '<p>Masih &lt; 1 secara finansial, tetapi jauh lebih baik dari 0,03 — karena porsi <i>investasi</i> setidaknya mengembalikan nilainya sedangkan pencegahan nyaris tak bernilai setelah didiskonto. Setuju atau tidak bergantung pada penerimaan tarif 6%; atas dasar CBA sosial (ireversibilitas, diskonto rendah) pencegahan bisa lebih bernilai dari yang ditunjukkan angka.</p>' } },

          { n: 'II',
            q: { en: 'Basic cash transfer of €200/month; for income above €100, every extra €1 reduces the transfer by €1 (100% marginal tax). Pierre earns €10/h, no other income. <b>(a)</b> Draw the monthly budget line with and without the program; at how many hours does his transfer reach zero? (label axes, intercepts, kinks). <b>(b)</b> What happens to Pierre’s hours and total income? <b>(c)</b> Now lower the marginal tax to 66.67%; draw the new budget line. <b>(d)</b> Compared with the 100% case, how does this change his hours and income?',
                 id: 'Bantuan tunai dasar €200/bln; untuk penghasilan di atas €100, tiap tambahan €1 mengurangi bantuan €1 (pajak marjinal 100%). Pierre €10/jam, tanpa penghasilan lain. <b>(a)</b> Gambar garis anggaran bulanan dgn & tanpa program; pada berapa jam bantuannya jadi nol? (beri label sumbu, titik potong, kelok). <b>(b)</b> Apa yang terjadi pada jam kerja & total pendapatan Pierre? <b>(c)</b> Turunkan pajak marjinal ke 66,67%; gambar garis baru. <b>(d)</b> Dibanding kasus 100%, bagaimana perubahan jam & pendapatannya?' },
            answer: { en: '(a) transfer = 0 at 30 hours; flat trap €100–€300; (b) works ≤10 h or >30 h; income stuck at €300; (c)–(d) 66.7% gives positive slope → works more.', id: '(a) bantuan = 0 pada 30 jam; jebakan datar €100–€300; (b) kerja ≤10 jam atau >30 jam; pendapatan terjebak €300; (c)–(d) 66,7% kemiringan positif → kerja lebih banyak.' },
            working: { en: '<p><b>(a)</b> Net income $y(h) = 10h + \\max(0,\\,200 - 1\\cdot\\max(0,\\,10h-100))$. The €100 <b>disregard</b> = 10 hours. The transfer is fully clawed back when earnings reach €100 + €200 = €300, i.e. at <b>h* = 30 hours</b>. The budget line: from <b>(0, €200)</b> up at slope 10 to (10, €300), then <b>FLAT at €300</b> from 10 to 30 hours (the 100% notch), then slope 10 again beyond 30 h (rejoining the no-program line $y=10h$).</p>' + FIG('welfare-bc', { w: 10, G: 200, t: 1, D: 100 }) +
                    '<p><b>(b)</b> Over 10–30 hours the 100% marginal tax means extra work earns <b>nothing</b> — a severe <span class="key">welfare trap</span>. A rational Pierre works <b>at most 10 hours</b> (keeping the full transfer, income €300) or jumps to <b>more than 30 hours</b>; he never works in the 10–30 range. Most likely total income stays at €300 with minimal work, so the program <b>reduces labour supply</b>.</p>' +
                    '<p><b>(c)</b> With a <b>66.67%</b> marginal tax, the clawback ends at income €100 + €200/0.6667 = €400 → <b>h* = 40 hours</b>. In the phase-out range the slope is $w(1-t) = 10 \\times 0.3333 = €3.33/h$ (positive, not flat).</p>' + FIG('welfare-bc', { w: 10, G: 200, t: 0.6667, D: 100 }) +
                    '<p><b>(d)</b> Because each extra hour now adds €3.33 (not €0), <b>work pays again</b> — the disincentive is much weaker, so Pierre <b>works more hours and earns more</b> than under the 100% tax. The trade-off: the gentler taper spreads the benefit further up the income scale (to 40 h), raising the program’s cost and the number of recipients.</p>',
                 id: '<p><b>(a)</b> Pendapatan bersih $y(h) = 10h + \\max(0,\\,200 - 1\\cdot\\max(0,\\,10h-100))$. <b>Pengecualian</b> €100 = 10 jam. Bantuan habis terpotong saat penghasilan mencapai €100 + €200 = €300, yaitu pada <b>h* = 30 jam</b>. Garis anggaran: dari <b>(0, €200)</b> naik kemiringan 10 ke (10, €300), lalu <b>DATAR di €300</b> dari 10 ke 30 jam (notch 100%), lalu kemiringan 10 lagi setelah 30 jam (kembali ke garis tanpa-program $y=10h$).</p>' + FIG('welfare-bc', { w: 10, G: 200, t: 1, D: 100 }) +
                    '<p><b>(b)</b> Di 10–30 jam, pajak marjinal 100% berarti kerja tambahan <b>tak menghasilkan apa-apa</b> — <span class="key">jebakan bansos</span> parah. Pierre rasional bekerja <b>maksimal 10 jam</b> (menahan bantuan penuh, pendapatan €300) atau melompat ke <b>lebih dari 30 jam</b>; tak pernah bekerja di rentang 10–30. Kemungkinan besar pendapatan tetap €300 dgn kerja minimal, jadi program <b>menurunkan penawaran tenaga kerja</b>.</p>' +
                    '<p><b>(c)</b> Dengan pajak marjinal <b>66,67%</b>, potongan berakhir di penghasilan €100 + €200/0,6667 = €400 → <b>h* = 40 jam</b>. Di rentang phase-out kemiringannya $w(1-t) = 10 \\times 0,3333 = €3,33/jam$ (positif, tak datar).</p>' + FIG('welfare-bc', { w: 10, G: 200, t: 0.6667, D: 100 }) +
                    '<p><b>(d)</b> Karena tiap jam tambahan kini menambah €3,33 (bukan €0), <b>kerja membayar lagi</b> — disinsentif jauh lebih lemah, jadi Pierre <b>bekerja lebih banyak dan berpenghasilan lebih</b> dari kasus 100%. Trade-off: taper lebih landai menyebar bantuan lebih jauh ke atas (hingga 40 jam), menaikkan biaya & jumlah penerima.</p>' } },

          { n: 'III',
            q: { en: '<b>(i)</b> Briefly explain (no diagram) some effects of Social Security on economic behaviour. <b>(ii)</b> Two-period model, diminishing marginal utility, income $20,000 (period 1) and $5,000 (period 2), interest 10%, can borrow/lend, no bequest. <b>(a)</b> Optimal consumption each period without Social Security? <b>(b)</b> Now a program takes $3,000 in period 1 and repays it with interest in period 2 — effect on saving?',
                 id: '<b>(i)</b> Jelaskan singkat (tanpa diagram) beberapa efek Jaminan Sosial pada perilaku ekonomi. <b>(ii)</b> Model dua periode, utilitas marjinal menurun, pendapatan $20.000 (periode 1) dan $5.000 (periode 2), bunga 10%, bisa pinjam/beri pinjaman, tanpa warisan. <b>(a)</b> Konsumsi optimal tiap periode tanpa Jaminan Sosial? <b>(b)</b> Kini program mengambil $3.000 di periode 1 dan membayar kembali dgn bunga di periode 2 — efek pada tabungan?' },
            answer: { en: '(i) saving (wealth-substitution↓, retirement↑, bequest↑) & earlier retirement; (ii a) c₁=c₂≈$12,857, saves ≈$7,143; (ii b) optimum unchanged, private saving falls $3,000.', id: '(i) tabungan (substitusi-kekayaan↓, pensiun↑, warisan↑) & pensiun dini; (ii a) c₁=c₂≈$12.857, menabung ≈$7.143; (ii b) optimum tetap, tabungan swasta turun $3.000.' },
            working: { en: '<p><b>(i)</b> Social Security changes behaviour mainly through <b>saving</b> and <b>retirement</b>. On saving, three effects: the <b>wealth-substitution effect</b> (SS wealth substitutes for private saving → saving ↓), the <b>retirement effect</b> (earlier retirement → must finance a longer retirement → saving ↑), and the <b>bequest effect</b> (save more to offset the intergenerational transfer → saving ↑); the net effect is ambiguous and empirical (Feldstein vs Leimer–Lesnoy). On work, SS wealth + the earnings test create an <b>implicit tax on continued work</b> → earlier retirement (Diamond–Gruber, Gruber–Wise).</p>' +
                    '<p><b>(ii a)</b> Lifetime wealth $= 20{,}000 + 5{,}000/1.1 = \\$24{,}545$. With diminishing marginal utility he <b>smooths</b> consumption. Setting $c_1=c_2$ on the budget $c_1 + c_2/1.1 = 24{,}545$ (i.e. save $S$: $20{,}000-S = 5{,}000+1.1S$):</p>' +
                    '<div class="formula">$$ 15{,}000 = 2.1\\,S \\Rightarrow S \\approx \\$7{,}143, \\quad c_1 = c_2 \\approx \\$12{,}857 $$</div>' +
                    '<p>He <b>saves ≈ $7,143</b> in period 1 (income is front-loaded). The optimum is where the indifference curve is tangent to the budget line ($MRS = 1+r$).</p>' + FIG('intertemporal', { r: 0.1, beta: 0.5, I0: 20, I1: 5 }) +
                    '<p><b>(ii b)</b> The program takes $3,000 now and repays $3,000 × 1.1 = $3,300 later — an <b>actuarially fair</b> trade at the same 10% rate. It just slides the endowment <i>along the same budget line</i>, so the <b>optimum is unchanged</b> ($c_1=c_2≈\\$12{,}857$). Private saving falls one-for-one to ≈ $7,143 − $3,000 = <b>$4,143</b>: the government now does $3,000 of the saving for him. <b>Total</b> saving is unchanged — Social Security <b>crowds out</b> private saving dollar-for-dollar in this pure model.</p>' + FIG('ss-crowdout', { r: 0.1, T: 3 }),
                 id: '<p><b>(i)</b> Jaminan Sosial mengubah perilaku terutama lewat <b>tabungan</b> dan <b>pensiun</b>. Pada tabungan, tiga efek: <b>efek substitusi-kekayaan</b> (kekayaan JS menggantikan tabungan swasta → ↓), <b>efek pensiun</b> (pensiun lebih dini → biayai pensiun lebih lama → ↑), dan <b>efek warisan</b> (menabung lebih untuk mengimbangi transfer antargenerasi → ↑); efek bersih ambigu & empiris (Feldstein vs Leimer–Lesnoy). Pada kerja, kekayaan JS + earnings test menciptakan <b>pajak implisit atas kerja lanjutan</b> → pensiun dini (Diamond–Gruber, Gruber–Wise).</p>' +
                    '<p><b>(ii a)</b> Kekayaan seumur hidup $= 20.000 + 5.000/1,1 = \\$24.545$. Dengan utilitas marjinal menurun ia <b>memuluskan</b> konsumsi. Tetapkan $c_1=c_2$ pada anggaran $c_1 + c_2/1,1 = 24.545$ (menabung $S$: $20.000-S = 5.000+1,1S$):</p>' +
                    '<div class="formula">$$ 15.000 = 2,1\\,S \\Rightarrow S \\approx \\$7.143, \\quad c_1 = c_2 \\approx \\$12.857 $$</div>' +
                    '<p>Ia <b>menabung ≈ $7.143</b> di periode 1 (pendapatan terkonsentrasi di awal). Optimum di titik singgung kurva indiferen dgn garis anggaran ($MRS = 1+r$).</p>' + FIG('intertemporal', { r: 0.1, beta: 0.5, I0: 20, I1: 5 }) +
                    '<p><b>(ii b)</b> Program mengambil $3.000 kini dan membayar $3.000 × 1,1 = $3.300 nanti — pertukaran <b>adil-aktuaria</b> pada tarif 10% yang sama. Ini hanya menggeser endowment <i>di garis anggaran yang sama</i>, jadi <b>optimum tak berubah</b> ($c_1=c_2≈\\$12.857$). Tabungan swasta turun satu-lawan-satu ke ≈ $7.143 − $3.000 = <b>$4.143</b>: pemerintah kini menabung $3.000 untuknya. Tabungan <b>total</b> tetap — Jaminan Sosial <b>menggusur</b> tabungan swasta dolar-per-dolar dalam model murni ini.</p>' + FIG('ss-crowdout', { r: 0.1, T: 3 }) } },

          { n: 'IV',
            q: { en: 'A country has four groups re private health insurance: G1 can’t afford but badly needs it; G2 can afford but won’t buy; G3 buys, spending half their income; G4 buys, spending almost all. <b>(1)</b> If the government provides free health care, how does it affect provision for each group (graph per group)? <b>(2)</b> Will private insurance disappear entirely? <b>(3)</b> If a private insurer lowers its premium, will any group buy more?',
                 id: 'Sebuah negara punya empat kelompok soal asuransi kesehatan swasta: K1 tak mampu tetapi sangat butuh; K2 mampu tetapi enggan beli; K3 beli, separuh penghasilan; K4 beli, hampir semua. <b>(1)</b> Jika pemerintah memberi kesehatan gratis, bagaimana dampaknya pada penyediaan tiap kelompok (grafik per kelompok)? <b>(2)</b> Apakah asuransi swasta hilang seluruhnya? <b>(3)</b> Jika asuransi swasta menurunkan premi, adakah kelompok yang membeli lebih?' },
            answer: { en: '(1) G1 gains most; G2 free-rides; G3/G4 crowd-out private; (2) no — private survives as top-up; (3) yes — lower price raises quantity demanded (G2 especially).', id: '(1) K1 untung terbesar; K2 free-ride; K3/K4 crowd-out swasta; (2) tidak — swasta bertahan sbg pelengkap; (3) ya — harga turun menaikkan kuantitas diminta (terutama K2).' },
            working: { en: '<p><b>(1) Effect of free public care, by group:</b></p><table><thead><tr><th>Group</th><th>Effect</th></tr></thead><tbody>' +
                    '<tr><td><b>G1</b> (needs, can’t afford)</td><td>Biggest welfare gain — they finally get coverage they could not buy. Free care fixes the <b>access/equity</b> failure (a merit good).</td></tr>' +
                    '<tr><td><b>G2</b> (can afford, won’t buy)</td><td>They now get coverage free → <b>free-ride</b>; the public program removes the cost of their earlier under-insurance.</td></tr>' +
                    '<tr><td><b>G3</b> (buys, half income)</td><td>Free public care is a substitute → <b>crowds out</b> their private purchase; they shift spending to other goods.</td></tr>' +
                    '<tr><td><b>G4</b> (buys, almost all)</td><td>Their basic needs are now covered free; they likely keep buying <b>private top-up/premium</b> care for quality/extras.</td></tr></tbody></table>' +
                    '<p>Graphically, each group has a different demand/willingness-to-pay for health care; a price of zero pushes every group to the quantity where marginal benefit = 0, but the <i>gain</i> differs (largest for G1, a pure transfer for G2, crowd-out for G3, top-up for G4). The moral-hazard logic below applies: free care (price 0) → over-consumption + deadweight loss.</p>' + FIG('moral-hazard', { coins: 0, B: 0.8 }) +
                    '<p><b>(2) No, private insurance does not vanish.</b> Free public care provides a <b>basic floor</b>, but G3 and especially G4 will buy <b>supplementary/private</b> insurance for shorter queues, choice, and quality beyond the public package — a typical <b>two-tier</b> system (e.g. private top-up over a national scheme). Private insurance survives in the gap between the public floor and what richer groups want.</p>' +
                    '<p><b>(3) Yes.</b> Lowering the premium is a fall in price → a <b>movement along the demand curve</b>, raising quantity demanded. The group most likely to start/expand buying is <b>G2</b> (can afford, was unwilling at the old price) and possibly parts of G1 if it becomes affordable; G3 may also raise coverage. This is ordinary demand, distinct from the adverse-selection effect of pooling.</p>',
                 id: '<p><b>(1) Dampak kesehatan publik gratis, per kelompok:</b></p><table><thead><tr><th>Kelompok</th><th>Dampak</th></tr></thead><tbody>' +
                    '<tr><td><b>K1</b> (butuh, tak mampu)</td><td>Keuntungan kesejahteraan terbesar — akhirnya dapat cakupan yang tak bisa dibeli. Gratis memperbaiki kegagalan <b>akses/keadilan</b> (merit good).</td></tr>' +
                    '<tr><td><b>K2</b> (mampu, enggan beli)</td><td>Kini dapat cakupan gratis → <b>free-ride</b>; program publik menghapus biaya under-insurance mereka.</td></tr>' +
                    '<tr><td><b>K3</b> (beli, separuh penghasilan)</td><td>Kesehatan gratis jadi substitusi → <b>crowd-out</b> pembelian swasta; belanja dialihkan ke barang lain.</td></tr>' +
                    '<tr><td><b>K4</b> (beli, hampir semua)</td><td>Kebutuhan dasar kini gratis; kemungkinan tetap membeli <b>pelengkap/premium swasta</b> untuk kualitas/ekstra.</td></tr></tbody></table>' +
                    '<p>Secara grafis, tiap kelompok punya permintaan/kesediaan-membayar berbeda; harga nol mendorong semua ke kuantitas di mana manfaat marginal = 0, tetapi <i>keuntungannya</i> berbeda (terbesar K1, transfer murni K2, crowd-out K3, pelengkap K4). Logika moral hazard di bawah berlaku: gratis (harga 0) → konsumsi berlebih + DWL.</p>' + FIG('moral-hazard', { coins: 0, B: 0.8 }) +
                    '<p><b>(2) Tidak, asuransi swasta tak lenyap.</b> Kesehatan gratis memberi <b>dasar</b>, tetapi K3 dan terutama K4 akan membeli asuransi <b>pelengkap/swasta</b> untuk antrean lebih pendek, pilihan, dan kualitas di atas paket publik — sistem <b>dua-tingkat</b> khas. Swasta bertahan di celah antara dasar publik dan keinginan kelompok kaya.</p>' +
                    '<p><b>(3) Ya.</b> Menurunkan premi = penurunan harga → <b>pergerakan sepanjang kurva permintaan</b>, menaikkan kuantitas diminta. Yang paling mungkin mulai/menambah beli adalah <b>K2</b> (mampu, enggan pada harga lama) dan mungkin sebagian K1 jika terjangkau; K3 juga bisa menambah cakupan. Ini permintaan biasa, beda dari efek adverse selection.</p>' } }
        ] }
      ]
    }
  };
})();
