/* ============================================================================
   MAKRO · Glossary — registered on window.MAKRO_GLOSSARY.
   Compact bilingual term list spanning the whole UAS half (Weeks 8–14):
   open-economy / Mundell–Fleming, monetary policy & financial markets,
   expectations / labour-market mismatch / SDM-FF, exchange-rate & balance-
   sheet effects, macroprudential / MMT / DSGE, and the emerging issues
   (climate, crypto/CBDC, welfare). Each term: { group, term, def:{en,id} }.
   ============================================================================ */
(function () {
  window.MAKRO_GLOSSARY = [

    /* ---- Week 8: Capital flows, policy & the exchange rate ---- */
    { group: 'Open economy', term: 'Balance of payments (BOP)',
      def: { en: 'Record of a country’s transactions with the world: current account (CA) + capital & financial account (KA) ≈ 0 (plus reserves). A CA deficit must be financed by net capital inflows.',
             id: 'Catatan transaksi negara dengan dunia: transaksi berjalan (CA) + akun modal & finansial (KA) ≈ 0 (plus cadangan). Defisit CA harus dibiayai arus modal masuk neto.' } },
    { group: 'Open economy', term: 'Uncovered interest parity (UIP)',
      def: { en: 'i = i* + (Eᵉ − E)/E (+ risk premium). Domestic and foreign returns are equalised by expected depreciation; a risk premium opens a wedge in crises.',
             id: 'i = i* + (Eᵉ − E)/E (+ premi risiko). Imbal domestik dan asing disamakan oleh ekspektasi depresiasi; premi risiko membuka baji saat krisis.' } },
    { group: 'Open economy', term: 'BP curve',
      def: { en: 'Combinations of Y and i that keep the balance of payments in equilibrium; flatter when capital is more mobile, horizontal under perfect mobility.',
             id: 'Kombinasi Y dan i yang menjaga neraca pembayaran seimbang; makin landai saat modal makin mobile, horizontal pada mobilitas sempurna.' } },
    { group: 'Open economy', term: 'Mundell–Fleming model',
      def: { en: 'IS–LM–BP for an open economy. Policy effectiveness depends on the exchange-rate regime and capital mobility.',
             id: 'IS–LM–BP untuk ekonomi terbuka. Efektivitas kebijakan bergantung pada rezim nilai tukar dan mobilitas modal.' } },
    { group: 'Open economy', term: 'Impossible trinity (trilemma)',
      def: { en: 'A country can have only two of: free capital mobility, a fixed exchange rate, and independent monetary policy.',
             id: 'Negara hanya bisa memiliki dua dari: mobilitas modal bebas, nilai tukar tetap, dan kebijakan moneter independen.' } },
    { group: 'Open economy', term: 'FDI vs hot money',
      def: { en: 'FDI is long-horizon and sticky; portfolio/"hot money" flows are short-horizon and reverse quickly, driving sudden stops.',
             id: 'FDI berjangka panjang dan lengket; arus portofolio/"hot money" berjangka pendek dan cepat berbalik, memicu sudden stop.' } },
    { group: 'Open economy', term: 'Capital controls / macroprudential',
      def: { en: 'Measures (taxes, limits, reserve requirements) that lean against destabilising capital flows when the trilemma binds.',
             id: 'Langkah (pajak, batas, giro wajib) yang melawan arus modal yang mendestabilisasi saat trilema mengikat.' } },

    /* ---- Week 9: Monetary policy & financial markets ---- */
    { group: 'Monetary policy', term: 'Reserve money (RM / M0)',
      def: { en: 'Base money issued by the central bank = currency + bank reserves. The raw material of broad money.',
             id: 'Uang primer yang diterbitkan bank sentral = uang kartal + cadangan bank. Bahan baku uang luas.' } },
    { group: 'Monetary policy', term: 'Money multiplier',
      def: { en: 'M1/RM = 1/[c + rr(1−c)]. Collapses when the currency ratio c or reserve ratio rr rises (e.g. bank runs, 1929–33).',
             id: 'M1/RM = 1/[c + rr(1−c)]. Runtuh saat rasio kartal c atau rasio cadangan rr naik (mis. bank runs, 1929–33).' } },
    { group: 'Monetary policy', term: 'Fisher identity',
      def: { en: 'r = i − πᵉ. Deflation (πᵉ < 0) raises the real rate even if the nominal rate is low — deepening the Great Depression.',
             id: 'r = i − πᵉ. Deflasi (πᵉ < 0) menaikkan suku bunga riil meski nominal rendah — memperdalam Depresi Besar.' } },
    { group: 'Monetary policy', term: 'Sterilised intervention',
      def: { en: 'Inject base money then sell securities to neutralise it: M2 can rise while M0 stays flat (BI–MoF COVID burden-sharing).',
             id: 'Suntik uang primer lalu jual surat berharga untuk menetralkannya: M2 bisa naik sementara M0 datar (burden-sharing BI–Kemenkeu COVID).' } },
    { group: 'Monetary policy', term: 'Burden sharing',
      def: { en: 'BI–Ministry-of-Finance bond-buying arrangement funding the COVID PEN programme without inflating base money.',
             id: 'Kesepakatan pembelian obligasi BI–Kemenkeu yang membiayai program PEN COVID tanpa menggelembungkan uang primer.' } },
    { group: 'Monetary policy', term: 'Inflation targeting (IT)',
      def: { en: 'Framework where the central bank commits to an inflation target (BI: 2.5%±1%) and steers the policy rate to meet it.',
             id: 'Kerangka di mana bank sentral berkomitmen pada target inflasi (BI: 2,5%±1%) dan mengarahkan suku bunga kebijakan untuk mencapainya.' } },
    { group: 'Monetary policy', term: 'Taylor rule',
      def: { en: 'Policy-rate reaction to the inflation gap and output gap; the open-economy revision adds the exchange rate and the foreign rate.',
             id: 'Reaksi suku bunga kebijakan terhadap gap inflasi dan gap output; revisi ekonomi terbuka menambah nilai tukar dan suku bunga asing.' } },
    { group: 'Monetary policy', term: 'Time inconsistency',
      def: { en: 'Today’s optimal policy stops being optimal later; discretion creates an inflation bias that credibility/rules remove.',
             id: 'Kebijakan optimal hari ini berhenti optimal kelak; diskresi menciptakan bias inflasi yang dihapus kredibilitas/aturan.' } },

    /* ---- Week 10: Expectations, mismatch & SDM-FF ---- */
    { group: 'Expectations & labour', term: 'Expectations-augmented Phillips curve',
      def: { en: 'πₜ = πᵉ − α(uₜ − uₙ). The short-run position depends on expected inflation; vertical in the long run at the natural rate uₙ.',
             id: 'πₜ = πᵉ − α(uₜ − uₙ). Posisi jangka pendek bergantung inflasi ekspektasi; vertikal jangka panjang di tingkat alamiah uₙ.' } },
    { group: 'Expectations & labour', term: 'Credibility',
      def: { en: 'Degree to which the public believes the central bank’s inflation commitment; higher credibility lowers πᵉ and the sacrifice ratio.',
             id: 'Sejauh mana publik percaya komitmen inflasi bank sentral; kredibilitas tinggi menurunkan πᵉ dan sacrifice ratio.' } },
    { group: 'Expectations & labour', term: 'Labour-market mismatch',
      def: { en: 'Disconnect between workers’ skills/location and employers’ needs — vertical (over/under-qualification), horizontal (wrong field), spatial.',
             id: 'Keterputusan antara keterampilan/lokasi pekerja dan kebutuhan pemberi kerja — vertikal (over/under-kualifikasi), horizontal (salah bidang), spasial.' } },
    { group: 'Expectations & labour', term: 'Beveridge curve',
      def: { en: 'Downward-sloping locus of the vacancy rate vs the unemployment rate; an outward shift signals worse matching efficiency.',
             id: 'Lokus menurun tingkat lowongan vs tingkat pengangguran; pergeseran ke luar menandakan efisiensi matching memburuk.' } },
    { group: 'Expectations & labour', term: 'Matching function',
      def: { en: 'H = μ·Vᵅ·U¹⁻ᵅ — turns vacancies V and unemployed U into hires H; μ is (unobservable) matching efficiency.',
             id: 'H = μ·Vᵅ·U¹⁻ᵅ — mengubah lowongan V dan penganggur U menjadi hires H; μ adalah efisiensi matching (tak teramati).' } },
    { group: 'Expectations & labour', term: 'Okun’s law',
      def: { en: '(Ȳ − Y)/Ȳ = c(u − ū): the output gap maps to the unemployment gap; ~2% growth holds unemployment constant.',
             id: '(Ȳ − Y)/Ȳ = c(u − ū): gap output dipetakan ke gap pengangguran; pertumbuhan ~2% menjaga pengangguran tetap.' } },
    { group: 'Expectations & labour', term: 'SDM-FF',
      def: { en: 'Supply–Demand macro-econometric model with financial frictions: stochastic (estimated) equations + identities, estimated by 3SLS.',
             id: 'Model makro-ekonometrik penawaran–permintaan dengan friksi keuangan: persamaan stokastik (diestimasi) + identitas, diestimasi 3SLS.' } },

    /* ---- Week 11: Exchange rate & balance-sheet effects ---- */
    { group: 'Exchange rate', term: 'ER regime spectrum',
      def: { en: 'From hard peg (currency union/board/dollarisation) → soft peg (band/crawl) → managed float → free float.',
             id: 'Dari hard peg (uni mata uang/dewan/dolarisasi) → soft peg (band/crawl) → managed float → free float.' } },
    { group: 'Exchange rate', term: 'De jure vs de facto regime',
      def: { en: 'Officially declared regime vs the one actually followed; "fear of floating" makes many de jure floats de facto pegs.',
             id: 'Rezim yang dideklarasikan resmi vs yang benar-benar dijalankan; "fear of floating" membuat banyak float de jure jadi peg de facto.' } },
    { group: 'Exchange rate', term: 'NER / RER / NEER / REER',
      def: { en: 'Nominal ER; real ER (= NER·P*/P, competitiveness); nominal & real effective ERs (trade-weighted baskets).',
             id: 'NT nominal; NT riil (= NT·P*/P, daya saing); NT efektif nominal & riil (keranjang tertimbang perdagangan).' } },
    { group: 'Exchange rate', term: 'Balance-sheet effect',
      def: { en: 'With foreign-currency debt, a depreciation raises the local-currency value of liabilities, cutting net worth and investment.',
             id: 'Dengan utang valas, depresiasi menaikkan nilai kewajiban dalam mata uang lokal, memangkas kekayaan bersih dan investasi.' } },
    { group: 'Exchange rate', term: 'Currency & maturity (double) mismatch',
      def: { en: 'Borrowing short and in foreign currency while earning long and in local currency — the core EM crisis vulnerability.',
             id: 'Meminjam jangka pendek dan dalam valas sementara berpenghasilan jangka panjang dan dalam mata uang lokal — kerentanan inti krisis negara berkembang.' } },
    { group: 'Exchange rate', term: 'Contractionary depreciation',
      def: { en: 'When the balance-sheet channel dominates the net-export channel, a weaker currency lowers output (backward-bending AD).',
             id: 'Ketika kanal neraca mendominasi kanal ekspor neto, mata uang lebih lemah menurunkan output (AD membengkok ke belakang).' } },

    /* ---- Week 12: Macroprudential, MMT, DSGE ---- */
    { group: 'Frameworks', term: 'Macroprudential policy',
      def: { en: 'System-wide regulation leaning against the build-up of financial risk (countercyclical buffers, LTV/DTI caps, the credit cycle).',
             id: 'Regulasi sistem-luas yang melawan penumpukan risiko keuangan (buffer countercyclical, batas LTV/DTI, siklus kredit).' } },
    { group: 'Frameworks', term: 'Procyclicality',
      def: { en: 'Tendency of the financial system to amplify the cycle — credit and asset prices boom in good times, collapse in bad.',
             id: 'Kecenderungan sistem keuangan memperkuat siklus — kredit dan harga aset meledak saat baik, runtuh saat buruk.' } },
    { group: 'Frameworks', term: 'MMT (Modern Monetary Theory)',
      def: { en: 'View that a currency-issuing government is not revenue-constrained but inflation-constrained; taxes/bonds manage demand, not "fund" spending.',
             id: 'Pandangan bahwa pemerintah penerbit mata uang tidak dibatasi penerimaan melainkan inflasi; pajak/obligasi mengelola permintaan, bukan "mendanai" belanja.' } },
    { group: 'Frameworks', term: 'Functional finance',
      def: { en: 'The MMT principle that fiscal policy should target real outcomes (full employment, stable prices), not a balanced budget per se.',
             id: 'Prinsip MMT bahwa kebijakan fiskal harus menargetkan hasil riil (kesempatan kerja penuh, harga stabil), bukan anggaran berimbang itu sendiri.' } },
    { group: 'Frameworks', term: 'DSGE model',
      def: { en: 'Dynamic Stochastic General Equilibrium: micro-founded model with optimising agents, rational expectations, nominal rigidities and shocks.',
             id: 'Dynamic Stochastic General Equilibrium: model berfondasi mikro dengan agen pengoptimal, ekspektasi rasional, kekakuan nominal, dan guncangan.' } },
    { group: 'Frameworks', term: 'Euler equation',
      def: { en: 'Consumption-smoothing condition at the heart of DSGE: marginal utility today = expected discounted marginal utility tomorrow ×(1+r).',
             id: 'Kondisi pemerataan konsumsi di inti DSGE: utilitas marjinal hari ini = ekspektasi utilitas marjinal besok yang didiskon ×(1+r).' } },
    { group: 'Frameworks', term: 'Lucas critique',
      def: { en: 'Estimated policy relationships break down when policy changes, because expectations adjust — motivating micro-founded (DSGE) models.',
             id: 'Hubungan kebijakan yang diestimasi runtuh saat kebijakan berubah, karena ekspektasi menyesuaikan — memotivasi model berfondasi mikro (DSGE).' } },

    /* ---- Week 13: Climate, crypto/CBDC, welfare ---- */
    { group: 'Emerging issues', term: 'ENSO / El Niño – La Niña',
      def: { en: 'Pacific climate oscillation; El Niño brings drought (1997–98 Indonesian fires), La Niña brings floods — a macro supply shock.',
             id: 'Osilasi iklim Pasifik; El Niño membawa kekeringan (kebakaran Indonesia 1997–98), La Niña membawa banjir — guncangan penawaran makro.' } },
    { group: 'Emerging issues', term: 'Solow residual (TFP)',
      def: { en: 'Output growth not explained by input growth: gY − αgK − (1−α)gN = (1−α)gA. Climate damage drags on gA.',
             id: 'Pertumbuhan output yang tak dijelaskan pertumbuhan input: gY − αgK − (1−α)gN = (1−α)gA. Kerusakan iklim menghambat gA.' } },
    { group: 'Emerging issues', term: 'Damage function D(T)',
      def: { en: 'Climate-loss term, Nordhaus-style D = αT², entering output as Y = f(K,L,A·(1−D(T))) — a supply-side (AS) shock.',
             id: 'Suku kerugian iklim, gaya Nordhaus D = αT², masuk output sebagai Y = f(K,L,A·(1−D(T))) — guncangan sisi-penawaran (AS).' } },
    { group: 'Emerging issues', term: 'Emissions Trading System (ETS)',
      def: { en: 'Cap-and-trade carbon market: a falling cap plus tradable allowances; the EU ETS is the leading compliance market.',
             id: 'Pasar karbon cap-and-trade: cap yang menurun plus jatah yang dapat diperdagangkan; EU ETS pasar kepatuhan utama.' } },
    { group: 'Emerging issues', term: 'Cryptocurrency',
      def: { en: 'Digital money secured by cryptography on a distributed blockchain ledger, needing no bank to verify transactions.',
             id: 'Uang digital yang diamankan kriptografi pada buku besar blockchain terdistribusi, tanpa bank untuk memverifikasi transaksi.' } },
    { group: 'Emerging issues', term: 'CBDC',
      def: { en: 'Central bank digital currency — a digital liability of the central bank. Two-tier preserves bank intermediation; retail/direct risks disintermediation.',
             id: 'Mata uang digital bank sentral — kewajiban digital bank sentral. Dua-tingkat menjaga intermediasi bank; ritel/langsung berisiko disintermediasi.' } },
    { group: 'Emerging issues', term: 'Disintermediation',
      def: { en: 'Migration of deposits out of banks (e.g. to a retail CBDC), shrinking the deposit base that funds bank credit.',
             id: 'Migrasi deposito keluar dari bank (mis. ke CBDC ritel), mengecilkan basis deposito yang mendanai kredit bank.' } },
    { group: 'Emerging issues', term: 'Loans create deposits',
      def: { en: 'Modern money-creation view: banks create new deposit money (M2) when they lend; money is destroyed on repayment.',
             id: 'Pandangan penciptaan uang modern: bank menciptakan uang deposito baru (M2) saat meminjamkan; uang dihancurkan saat pelunasan.' } },
    { group: 'Emerging issues', term: 'Poverty elasticities (α, β)',
      def: { en: 'α = elasticity of the poverty line w.r.t. prices; β = elasticity of poor incomes w.r.t. income. α < β ⇒ poverty worsens.',
             id: 'α = elastisitas garis kemiskinan terhadap harga; β = elastisitas pendapatan miskin terhadap pendapatan. α < β ⇒ kemiskinan memburuk.' } },
    { group: 'Emerging issues', term: 'Centripetal vs centrifugal (Piketty r>g)',
      def: { en: 'Centripetal forces concentrate wealth, centrifugal forces spread it; when r > g capital compounds faster than growth, concentrating wealth.',
             id: 'Gaya sentripetal memusatkan kekayaan, sentrifugal menyebarkannya; saat r > g kapital berbunga lebih cepat dari pertumbuhan, memusatkan kekayaan.' } },
    { group: 'Emerging issues', term: 'Non-formal (informal) sector',
      def: { en: 'Informal employment (≈56–60% in Indonesia) that absorbs shocks: contractionary policy reshuffles activity into it.',
             id: 'Pekerjaan informal (≈56–60% di Indonesia) yang menyerap guncangan: kebijakan kontraktif mengalihkan aktivitas ke sana.' } },

    /* ---- Week 14: Synthesis / workhorse model ---- */
    { group: 'Synthesis', term: 'Workhorse (WH) model',
      def: { en: 'Azis’s unifying macro system of 5 interacting markets (goods, money, ER/financial/capital, labour) run across short, medium and long run.',
             id: 'Sistem makro pemersatu Azis dari 5 pasar yang berinteraksi (barang, uang, NT/finansial/kapital, tenaga kerja) lintas jangka pendek, menengah, panjang.' } },
    { group: 'Synthesis', term: 'Three-pronged approach',
      def: { en: 'Course design: Phase 1 a simple model → Phase 2 an integrated model → Phase 3 emerging issues, applied to the Indonesian case.',
             id: 'Desain kursus: Fase 1 model sederhana → Fase 2 model terintegrasi → Fase 3 isu baru, diterapkan pada kasus Indonesia.' } },
    { group: 'Synthesis', term: 'Phillips relation',
      def: { en: 'πₜ − πₜ₋₁ = −α(uₜ − uₙ): change in inflation falls as unemployment rises above the natural rate (medium-run link).',
             id: 'πₜ − πₜ₋₁ = −α(uₜ − uₙ): perubahan inflasi turun saat pengangguran naik di atas tingkat alamiah (kaitan jangka menengah).' } },
    { group: 'Synthesis', term: 'Financial accelerator',
      def: { en: 'Two-way amplification between macro and finance: net worth gates credit, so shocks are magnified through balance sheets.',
             id: 'Amplifikasi dua arah antara makro dan keuangan: kekayaan bersih membatasi kredit, sehingga guncangan diperbesar lewat neraca.' } }
  ];
})();
